const messages = {
    CREATED_SUCCESS: 'Created successfully',
    UPDATED_SUCCESS: 'Updated successfully',
    TOKEN_EXPIRED: 'Token expired',

    FAILED_TO_AUTHENTICATE: 'Failed to authenticate',

    INVALID_USER: 'User does not exist',
    INVALID_TOKEN: 'Invalid Token!',
    INVALID_REQUEST: 'Invalid Request!',

    IS_REQUIRED: 'is required',
    SHOULD_BE_STRING: 'should be string',
    SHOULD_BE_NUMBER: 'should be number',
    MUST_BE_A_BOOLEAN: 'must be a boolean',
    SHOULD_BE_DATE: 'should be date',
    MUST_BE_LESS_THAN_OR_EQUAL_TO: 'must be less than or equal to',
    MUST_BE_EQUAL_TO: 'must be equal to',
    MUST_BE_LARGER_THAN_OR_EQUAL_TO: 'must be greater than or equal to',
    IS_NOT_ALLOWED_TO_BE_EMPTY: 'is not allowed to be empty',
    ALLOW_ONLY_ALPHA_NUMERIC: 'must only contain alpha-numeric characters',
    MUST_BE_A_VALID_EMAIL: 'must be a valid email',
    SOMETHING_WENT_WRONG: 'Something went wrong',

    NO_RECORD: 'No record found',
    ALREADY_ADDED: 'Already added',
    EMAIL_EXIST: 'Email is already exist',
    DELETED_SUCCESS: 'Deleted successfully',
    INVOICE_ALREADY_PAID: 'Invoice already paid',
    INVALID_TRANSACTION_DETAILS: 'Invalid transaction details',
    INVALID_BANK_ACCOUNT: 'Invalid bank account',
    INVALID_PASSWORD: 'Please enter valid password',
    RESET_PASS_LINK: 'Your reset password link has been sent to your email',
    ALREADY_VERIFIED: 'You Are Already Verified ',
    OTP_VERIFIED: 'OTP verified',
    OTP_EXPIRED: 'OTP expired',
    PASSWORD_CHANGE_SUCCESS: 'Password changed successfully',
    INVALID_EMAIL: 'This email does not exist',
    ALLOW_ONLY: 'must be one of',
    VERIFIED_EMAIL:'Your Email is Successfully Verified',
    VERIFICATION_ERROR:'You have an email verification error',

    REGISTERED_SUCCESS:'You are registered successfully, please check your email for email verification',
    REQUEST_SUCCESS:'Your Request has been Submitted',
    EMAIL_NOT_EXIST:'This email is not registered',
    TASK_CREATED:'Task has been created successfully',
    TASK_EXISTS:'Task Already exists',
    APP_REQUEST_EXIST:'Already requested',
    ALREADY_EXISTS:'Already exists',
    TOKEN_ERROR:'Invalid Token',
    UNAUTHORIZED:'You are not authorized',
    USER_NOT_EXISTS:'User not exists',
    KID_CREATED:'Kid created successfully',
    KID_NOT_EXISTS:'Kid not exists',
    PARENT_NOT_EXISTS:'parent id not exists',
    User_Blocked:'Your account has been blocked',
    User_Deleted:'Your account has been deleted',
    RULES_PAUSED:'Rules are now paused successfully',
    KID_DEVICE_NOT_EXISTS:'Kid device not exists',
    TIME_EXTENSION_REQUESTED:'Your request for time extension has been successfully submitted',
    TASK_NOT_EXISTS:'Task not exists',

    APP_ACTIVITY_LOGGED:'Your app activity logged successfully',
    GET_APP_ACTIVITY_LOGGED:'Your ACtivity have been displayed successfully',

    WEB_ACTIVITY_LOGGED:'Your web activity logged successfully',
    KID_CHAT_NOT_EXISTS: 'chat not exists',
    FILE_UPLOAD:'Your file has been uploaded',
    APP_NOT_EXISTS:'App not exists',
    KID_APP_ADDED:'Kid apps has been added',
    APP_ALREADY_EXISTS:'app already exists',
    WEBSITE_ALREADY_EXISTS:'website already exists',
    WEBSITE_CREATED:'website added successfully',
    WEBSITE_NOT_EXISTS:'website not exists',
    OLD_PASS_INCORRECT:'Your old password is incorrect',
    DEVICE_NOT_EXISTS:'Device not exists',
    DETAILS_UPDATE:'Details has been updated',
    APP_STATUS_UPDATED:'app status successfully updated',
    SUBSCRIPTION_UPDATED:'subscription successfully updated',
    PHONE_MUST_BE_CORRECT:'please enter valid phone number',
    DATA_FETCH:"fetched data",
    USER_BLOCKED:"Parent is blocked",
    USER_UNBLOCKED:"Parent is unblocked",
    USER_DELETED:"Parent is deleted",
    PIN_CODE_GENERATE:'pin code successfully generated',
    SLOT_CREATED:'slot has been created successfully',
    PINCODE_NOT_EXISTS:'pin code does not exists',
    PINCODE_INCORRECT:'pin invalid',
    Remove_Restriction:'All restrictions on this device have been removed successfully.',
    NO_DATA_LOG:'No data found',
    MUST_HAVE_FOUR_DIGIT: ' enter 4 digit pincode',
    FEEDBACK_SUBMIT:'Your feedback has been submitted',
    GENERATE_PASSWORD:'Additional parent has been created successfully and link has been sent to this given email for password generate',
    DEVICE_DELETED:'Your device has been deleted successfully',
    HEADER_NOT_FOUND:'Timezone not found',
    KID_DELETED:'Kid deleted successfully',
    SLOT_NOT_EXISTS:'Slot not exists',
    NOT_VERIFY_EMAIL:'your account is not verified',
    NO_TIME_REQUEST:'No time request',
    // TIME_EXTENSION_REQUESTED:'time extension approved  successfully',
    NOT_EXISTS:'additional parent not exists',
    APP_CATEGORY_NOT_EXISTS:'App category not exists',
    WEB_CATEGORY_NOT_EXISTS:'Web category not exists',
    CODEBlock:'Code is blocked',
    CODEUNBlock:'Code is unblocked',
    CODEDELETED:'Code is deleted',
    PROMOTIONBLOCK:'Brand Promotion is blocked',
    PROMOTIONUNBLOCK:'Brand Promotion is unblocked',
    FORGET_PIN_LINK_GENERATED:'Forgot pincode link has been sent to this given email',
    RESET_PIN_LINK_GENERATED:'Reset pincode link has been sent to this given email',
    WEBISTE_UPDATED:'Website url has been successfully updated',
    ID_NOT_NULl:'Id can not be empty',
    DATA_DELETED:'Data has been deleted successfully',
    ACCOUNT_DELETED:'Your account has been deleted successfully',
    PINCODE_NOT_EXISTS:'PINCODE not generated yet,please create PINCODE first',
    OLD_PIN_INCORRECT:'old pin is incorrect',
    IS_DELETED:'This email has been deleted in past please contact to admin',
    EMAIL_NOT_EXISTS:'Email is not registered',
    EMAIL_NOT_VERIFY:'Email is not verified',
    TIME_REQUEST_NOT_EXISTS:'Time request not exists',
    EMAIL_EXIST_NOT_VERIFY:'You are registered already please verify your email',
    AGAIN_SUCCESS_EMAIL:'A verification email has been sent to your account. Please validate it.',
    KID_CONTACT_ADDED:'Kid contact numbers has been added successfully',
    CONTACT_NOT_EXISTS:'No contact found',
    LANGCHANGE:'Language change Successfully',
    TRANSLATIONCHANGE:'Translation change Successfully',
    LANGTRANSLATION:'Language translation change Successfully',
    LANGUAGEEXISTS: 'Language Already Exists',
    TRANSLATIONEXISTS:'Translation Already Exists',
    LANGTRANSLATIONEXISTS:'Language Translation Already Exists',
    DEVIEC_ID_NOT_EXISTS:'Device id not exists',
    KID_DEVICE_NOT_EXISTS:'Kid device not exists',
    PERMISSION_UPDATED:'Permission updated successfully',
    PERMISSION_NOT_EXISTS:'Permission not exists',
    KEYSTROKE_STATUS_UPDATED:'keystroke status has been updated successfully',
    KID_ACTIVITY_LOGGED:'Kid Activity has been logged successfully',
    RATING_NOT_EXISTS:'Rating not exists',
    TASK_STATUS_UPDATED:'Task status has been updated successfully',
    SETTING_APP_STATUS_UPDATED:'Setting app status has been update successfully',
    LANGCHANGE:'Language change Successfully',
    TRANSLATIONCHANGE:'Translation change Successfully',
    LANGTRANSLATION:'Language translation change Successfully',
    LANGUAGEEXISTS: 'Language Already Exists',
    TRANSLATIONEXISTS:'Translation Already Exists',
    LANGTRANSLATIONEXISTS:'Language Translation Already Exists',
    MANNUAL_SCREENSHOT_UPDATED: 'Mannual screenshot updated successfully',
    MANNUAL_SCREENSHOT_REQUEST: 'Mannual screenshot request saved successfully',
    KID_CONTACT: 'Kid contact request saved successfully',
    DEVICE_SETTING: 'Device Setting updated successfully',
    WIPE_DATA: "Device data is wiped",
    BLOCK_DEVICE: "Device is blocked",
    DELETE_DATA: "Device Data is deleted",
    DEVICE_ASSIGNED:"Device has been assigned succesfully",
    WEB_CATEGORIES:"Web categoried fetched successfully",
    WEB_WEBSITES:"Websites fetched successfully",
    SOUND_ALERT: "Sound alert is send to device",
    DEVICE_ASSIGNED:"Device has been assigned succesfully",
    NO_DEVICE_TOKEN_NOT_EXISTS:"Device token not exist",
    TIME_SUPERVISION_ACTIVATED:'Time supervision has been activated successfully',
    CATEGORYBLOCKED: "Category has been blocked.",
    CATEGORYUNBLOCKED: "Category has been unblocked.",
    GEOFENCE_ADDED_SUCCESSFULLY:'Geofence has been added successfully',
    SCREENSHOT_SETTINGS:'Screenshot settings has been updated successfully',
    SET_RULES_ADDED_SUCCESSFULLY:'Set rules settings has been added successfully',
    INVALID_CASE:'Invalid case. Please enter correct case',
    CERTIFIED_DEVICE_EXIST:"Certified device already exist",
    CERTIFIED_DEVICE_ADDED:"Certified device has been added successfully",
    COPY_SETTINGS:'Copy settings has been added successfully',
    SUBSCRIPTION_EXISTS:'subscription already exists',
    CATEGORY_EXIST: 'Web category already exist',
    DATA_NOT_EXISTS:'Data not exists',
    LOGIN_SUCCESS:'login successfuly',
    WEB_CATEGORY_ADDED:'Web category added successfully',
    WEB_CATEGORY_UPDATED:'Web category updated successfully',
    RULES_NOT_EXISTS:'Rules not exists',
    CERTIFIED_DEVICE_NOT_EXISTS:'Certified device not exist',
    CERTIFIED_DEVICE_DELETED: 'Certified device is deleted successfully',
    GENERATE_PASSWORD_SUCCESSFULLY:'Your password has been successfully generated.',
    USER_NOTIFICATION_NOT_EXIST:'User notification does not exist',
    NOTIFICATION_DELETED:'Notification deleted successfully',
    ACTIVITY_DELETED:'Activity has been deleted successfully',
    is_device_time_supervision_enabled:'My screen time is monitoring.',
    is_block_web_and_app_enabled:'My block app and website is monitoring.',
    is_warn_kid_by_alert_enabled:'My warn activities is under supervision',
    is_allow_and_monitor_parents_enabled:'My device time is under supervision',
    is_screenshot_settings_enabled:'My Screenshot seetings is under supervision',
    is_capture_when_accessing_blocked_site:'My blocked website is under supervisio',
    is_capture_when_badwords:'My bad words is under supervision',
    is_set_geofence_enabled:'My location is under supervision',
    is_enable_supervision:'My device is under supervision',
    web_supervision:'My device web activity is under supervision',
    web_safe_search:'My device safe search is under supervision',
    web_safe_search_youtube:'My device safe search youtube is under supervision',
    install_new_apps:'My app installation is under supervision',
    is_keystroke_setting:'My device keystroke settings is under supervision',
    is_video_monitoring:'My device video monitoring is under supervision',
    is_nudity_monitoring:'My device nudity activity is under supervision',
    is_block_addition_new_contact:'New contacts is under supervision',
    USER_NOT_EXISTS:'User not exist',
    SEND_ALERT:'Alert has been sent successfully',
    CONTACT_BLOCKED:'Contact blocked successfully',
    EMAIL_PASSWORD_UPDATED: 'Admin email and password updated successfully',
    ALERT_SENT:'Alert has been sent successfully',
    CONTACT_BLOCKED:'Contact blocked successfully',
    GEOFENCE_UPDATED_SUCCESSFULLY:'Geofence location has been updated successfully',
    CATEGORY_STATUS_UPDATED:'Category status updated successfully',
    PARENT_REFERRAL_EXISTS:'Parent referral already exist',
    PARENT_REFERRAL_UPDATED:'Parent referral updated',
    DEFAULT_SETTING: 'Admin default setting updated',
    INVALID_DEVICE_ID:'Invalid device id',
    PERMISSION_UPDATED:'Permission updated successfully',
    CONTACT_ACTIVATED:'Contacts has been activated for monitoring',
    RESTRICTION_REMOVED:'Restriction has been removed',
    DATA_SAVED:'Data saved successfully',
    DEVICE_UNLOCK_SUCCESS:'Device unlock successfully',
    ALERT_LOGGED:'Alert has been logged',
    ALERT_NOT_EXISTS:'Alerts not exists',
    KID_REQUEST_APPROVED:'Kid request has been approved',
    KID_REQUEST_REJECT:'Kid request has been rejected',
    PASSCODE_SENT:'Passcode sent successfully',
    DEVICE_ID_NOT_EXISTS:'Device id not exists',
    WRONG_KID_SELECTED:'You have selected a wrong kid',
    KID_NOT_ASSOCIATED:'Kid is not associated on this device',
    SUBSCRIPTION_NOT_EXIST:'Subscription not exist',
    REFUND_SUCCESSFULL:'Refund process completed successfully',
    ACCESS_TOKEN:'Access token generated successfully',
    LANGUAGE_NOT_EXIST:'Language not exists',
    SAFE_SEARCH_UPDATED:'Safe search keywords has been updated',
    SUBSCRIPTION_NOT_EXISTS:'Subscription not exists',
    SUBSCRIPTION_EXPIRED:'Subscription has been expired',
    SUBSCRIPTION_STATUS:'Subscription status',
    TASK_PENDING:'Task already pending',
    CODE_EXISTS:'Code Already exists',
    KID_CREATED:'Kid device created successfully',
    APP_TIME_UPDATED:'App time has been updated successfully',
    IS_READ:'Read successfully',
    RESPONSE_FROM_DB:'Fetch data from Database',
    RESPONSE_FROM_KLAZIFY:'Fetch data from Klazify',
    RESPONSE_FROM_WEBSHRINKER:'Fetch data from Webshrinker',
    ENABLE_SCREENSHOT_PERMISSION:'Please enable screenshot permission',
    ENABLE_SUPERVISION:'Please enable supervision first!',
    PLEASE_SELECT_KID:'Please select kid',
    PINCODE_ALREADY_EXISTS:'Emergency code already exists'
};

console.log(Object.entries(messages));
const arrayOfMsg = Object.entries(messages);
for(let i =0 ; i < arrayOfMsg.length ; i ++) {
    //query for inserting data into the table
    //connection.query("INSERT INTO message(key, value) VALUES(?,?)",[arratOfMsg[i][0],arratOfMsg[i][1]],(err, data) => {
    //})
}